# Generated by Django 2.2 on 2022-02-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220216_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catag',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
