# Generated by Django 2.2 on 2022-02-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_items_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
